Repository Particular/ServiceControl, pull requests merged in 2021-05, with the labels that each got.

#2532 Allow for ingestion from Quorum queues
  src/ServiceControl.Audit/Auditing/BodyStorage/BodyStorageFeature.cs
  src/ServiceControl.Transports.RabbitMQ/ServiceControl.Transports.RabbitMQ.csproj
  src/ServiceControl/Recoverability/Archiving/ArchiveAllInGroupHandler.cs
Labels: Feature

#2543 Add additional logging around group archive operations
  src/ServiceControl/Recoverability/Archiving/ArchiveAllInGroupHandler.cs
  src/ServiceControl/Recoverability/Archiving/ArchiveDocumentManager.cs
Labels: Improvement

#2541 Remove the version and key token from the message type header when publishing integration events
  src/ServiceControl.AcceptanceTests/Monitoring/ExternalIntegration/When_a_custom_check_fails.cs
  src/ServiceControl.UnitTests/ApprovalFiles/APIApprovals.PublicClr.approved.txt
  src/ServiceControl/ExternalIntegrations/ExternalIntegrationsFeature.cs
  src/ServiceControl/ExternalIntegrations/RemoveVersionInformationBehavior.cs
Labels: Bug
