Repository Particular/ServiceControl, pull requests merged in 2024-10, with the labels that each got.

#4490 RabbitMQQueueDetails parsing doesn't account for duplicated elements
  src/ServiceControl.Transports.RabbitMQ/RabbitMQBrokerQueueDetails.cs
  src/ServiceControl.Transports.RabbitMQ/RabbitMQQuery.cs
  src/ServiceControl.Transports.RabbitMQ/RabbitMQQueueDetails.cs
  src/ServiceControl.Transports.RabbitMQQuorumDirectRouting.Tests/ApprovalFiles/RabbitMQQuery_ResponseParsing_Tests.Should_fetch_queue_details_in_old_format.approved.txt
  src/ServiceControl.Transports.RabbitMQQuorumDirectRouting.Tests/ApprovalFiles/RabbitMQQuery_ResponseParsing_Tests.Should_handle_duplicated_json_data.approved.txt
  src/ServiceControl.Transports.RabbitMQQuorumDirectRouting.Tests/RabbitMQQuery_ResponseParsing_Tests.cs
  src/ServiceControl.Transports.Tests/TransportTestFixture.cs
Labels: Bug

#4484 Update to RavenDB 6.2
  .github/workflows/build-db-container.yml
  .github/workflows/container-integration-test.yml
  src/Directory.Packages.props
  src/ServiceControl.AcceptanceTests.RavenDB/Recoverability/MessageFailures/FailedMessageRetriesController.cs
  src/ServiceControl.Audit.Persistence.RavenDB/DatabaseSetup.cs
  src/ServiceControl.Audit.Persistence.RavenDB/RavenAuditDataStore.cs
  src/ServiceControl.Audit.Persistence.RavenDB/RavenExternalPersistenceLifecycle.cs
  src/ServiceControl.Audit.Persistence.Tests.RavenDB/SagaHistoryIndexTests.cs
  src/ServiceControl.Audit.Persistence/Infrastructure/QueryStatsInfo.cs
  src/ServiceControl.Audit/Infrastructure/WebApi/HttpResponseExtensions.cs
  src/ServiceControl.Persistence.RavenDB/DatabaseSetup.cs
  src/ServiceControl.Persistence.RavenDB/EventLogDataStore.cs
  src/ServiceControl.Persistence.RavenDB/RavenExternalPersistenceLifecycle.cs
  src/ServiceControl.Persistence/IEventLogDataStore.cs
  src/ServiceControl.Persistence/Infrastructure/QueryStatsInfo.cs
  src/ServiceControl.RavenDB/Container-README.md
  src/ServiceControl.RavenDB/Dockerfile
  src/ServiceControl.RavenDB/EmbeddedDatabase.cs
  src/ServiceControl.RavenDB/StartupChecks.cs
  src/ServiceControl.RavenDB/sc-container-startup.sh
  src/ServiceControl/Infrastructure/WebApi/HttpResponseExtensions.cs
  src/ServiceControlInstaller.Engine.UnitTests/Validation/SelfContainedRavenDBTest.cs
  src/container-integration-test/servicecontrol.yml
Labels: Feature

#4523 Report saga audit misconfigurations more prominently
  src/ServiceControl.UnitTests/ApprovalFiles/APIApprovals.CustomCheckDetails.approved.txt
  src/ServiceControl/CustomChecks/InternalCustomChecks/InternalCustomChecks.cs
  src/ServiceControl/SagaAudit/SagaAuditMisconfigurationCustomCheck.cs
  src/ServiceControl/SagaAudit/SagaUpdatedHandler.cs
Labels: Improvement

#4545 Fix endpoint name display and grouping for Usage
  src/Particular.LicensingComponent.UnitTests/ThroughputCollector/ThroughputCollector_SanitizedNameGrouping_Tests.cs
  src/Particular.LicensingComponent/ThroughputCollector.cs
  src/ServiceControl.Transports.ASBS/AzureQuery.cs
  src/ServiceControl.Transports/BrokerThroughput/BrokerThroughputQuery.cs
Labels: Bug

#4546 PostgreSQL - High CPU utilization due to large number of DELETE statements
  src/Directory.Packages.props
  src/ServiceControl.Transports.PostgreSql/PostgreSqlTable.cs
Labels: Bug

#4549 PostgreSQL - High CPU utilization due to large number of DELETE statements
  src/Directory.Packages.props
  src/ServiceControl.Transports.PostgreSql/PostgreSqlTable.cs
Labels: Bug

#4548 PostgreSQL - High CPU utilization due to large number of DELETE statements
  src/Directory.Packages.props
  src/ServiceControl.Transports.PostgreSql/PostgreSqlTable.cs
Labels: Bug
