Repository Particular/ServiceControl, pull requests merged in 2024-08, with the labels that each got.

#4387 "Setup and run" startup option to combine setup and run into one action
  src/ServiceControl.Audit/Program.cs
  src/ServiceControl.Audit/Properties/launchSettings.json
  src/ServiceControl.Infrastructure/IntegratedSetup.cs
  src/ServiceControl.Monitoring/Program.cs
  src/ServiceControl.Monitoring/Properties/launchSettings.json
  src/ServiceControl/Program.cs
  src/ServiceControl/Properties/launchSettings.json
Labels: Feature

#4328 cache sqltable query
  src/ServiceControl.Transports.SqlServer/QueueLengthProvider.cs
  src/ServiceControl.Transports.SqlServer/SqlNameHelper.cs
  src/ServiceControl.Transports.SqlServer/SqlTable.cs
Labels: stale

#4396 Connection leak in NServiceBus.RabbitMQ and vulnerabilities in dependency System.Text.Json and transitive dependency System.Formats.Asn1
  src/Directory.Packages.props
Labels: Bug

#4403 Exit setup-and-run mode if setup fails
  src/ServiceControl.Audit/Program.cs
  src/ServiceControl.Infrastructure/IntegratedSetup.cs
  src/ServiceControl.Monitoring/Program.cs
  src/ServiceControl/Program.cs
Labels: Bug
