Repository Particular/ServiceControl, pull requests merged in 2025-02, with the labels that each got.

#4767 Multiple options for configuring RavenDB client certificate
  src/ServiceControl.Audit.Persistence.RavenDB/RavenExternalPersistenceLifecycle.cs
  src/ServiceControl.Audit.Persistence.RavenDB/RavenPersistenceConfiguration.cs
  src/ServiceControl.Audit.Persistence.RavenDB/ServerConfiguration.cs
  src/ServiceControl.Persistence.RavenDB/RavenBootstrapper.cs
  src/ServiceControl.Persistence.RavenDB/RavenExternalPersistenceLifecycle.cs
  src/ServiceControl.Persistence.RavenDB/RavenPersistenceConfiguration.cs
  src/ServiceControl.Persistence.RavenDB/RavenPersisterSettings.cs
  src/ServiceControl.RavenDB/RavenClientCertificate.cs
Labels: Improvement

#4678 Update README.md
  README.md
Labels: stale

#4781 Added process time to log file entry
  src/ServiceControl.Infrastructure/LoggingConfigurator.cs
Labels: Improvement

#4780 I/O Timeouts can cause error and audit ingestion to silently stop
  src/Particular.LicensingComponent/AuditThroughput/AuditThroughputCollectorHostedService.cs
  src/Particular.LicensingComponent/BrokerThroughput/BrokerThroughputCollectorHostedService.cs
  src/ServiceControl.AcceptanceTesting/ScenarioWithEndpointBehaviorExtensions.cs
  src/ServiceControl.Audit/Auditing/AuditIngestion.cs
  src/ServiceControl.Audit/Auditing/ImportFailedAudits.cs
  src/ServiceControl.Audit/Infrastructure/Hosting/Commands/ImportFailedAuditsCommand.cs
  src/ServiceControl.Infrastructure.Metrics/MetricsReporter.cs
  src/ServiceControl.Infrastructure/AsyncTimer.cs
  src/ServiceControl.Infrastructure/ReadOnlyStream.cs
  src/ServiceControl.Infrastructure/Watchdog.cs
  src/ServiceControl.Monitoring/Infrastructure/RemoveExpiredEndpointInstances.cs
  src/ServiceControl.Monitoring/Infrastructure/ReportThroughputHostedService.cs
  src/ServiceControl.Persistence.RavenDB/ExternalIntegrationRequestsDataStore.cs
  src/ServiceControl.Persistence.RavenDB/FailedErrorImportDataStore.cs
  src/ServiceControl.RavenDB/EmbeddedDatabase.cs
  src/ServiceControl.Transports.ASBS/QueueLengthProvider.cs
  src/ServiceControl.Transports.ASQ/QueueLengthProvider.cs
  src/ServiceControl.Transports.Learning/QueueLengthProvider.cs
  src/ServiceControl.Transports.PostgreSql/QueueLengthProvider.cs
  src/ServiceControl.Transports.RabbitMQ/QueueLengthProvider.cs
  src/ServiceControl.Transports.SQS/QueueLengthProvider.cs
  src/ServiceControl.Transports.SqlServer/QueueLengthProvider.cs
  src/ServiceControl/CompositeViews/Messages/ScatterGatherApi.cs
  src/ServiceControl/CustomChecks/InternalCustomChecks/InternalCustomCheckManager.cs
  src/ServiceControl/Hosting/Commands/ImportFailedErrorsCommand.cs
  src/ServiceControl/Infrastructure/Metrics/MetricsReporterHostedService.cs
  src/ServiceControl/Monitoring/HeartbeatEndpointSettingsSyncHostedService.cs
  src/ServiceControl/Monitoring/HeartbeatMonitoringHostedService.cs
  src/ServiceControl/Operations/CheckRemotes.cs
  src/ServiceControl/Operations/ErrorIngestion.cs
Labels: Bug

#4795 Fix batch message deduplication logic to not update batch on already batched message - 5.11
  src/ServiceControl.Persistence.RavenDB/RetryDocumentDataStore.cs
Labels: Bug

#4796 Fix batch message deduplication logic to not update batch on already batched message - 6.3
  src/ServiceControl.Persistence.RavenDB/RetryDocumentDataStore.cs
Labels: Bug

#4834 Improving provenance of image
  .github/workflows/build-containers.yml
  .github/workflows/build-db-container.yml
  .github/workflows/container-integration-test.yml
  .github/workflows/push-container-images.yml
  src/ServiceControl.Audit/Dockerfile
  src/ServiceControl.Monitoring/Dockerfile
  src/ServiceControl/Dockerfile
Labels: Improvement

#4821 Update to Azure Service Bus 5
  src/Directory.Packages.props
  src/ServiceControl.Transports.ASBS.Tests/ServiceControl.Transports.ASBS.Tests.csproj
  src/ServiceControl.Transports.ASBS/ASBSTransportCustomization.cs
  src/ServiceControl.Transports.ASBS/AuthenticationMethod.cs
  src/ServiceControl.Transports.ASBS/Helper.cs
  src/ServiceControl.Transports.ASBS/SharedAccessSignatureAuthentication.cs
  src/ServiceControl.Transports.ASBS/TokenCredentialAuthentication.cs
  src/ServiceControl.Transports/ServiceControl.Transports.csproj
Labels: Improvement
