Repository Particular/ServiceControl, pull requests merged in 2025-03, with the labels that each got.

#4863 Limit throughput data returned to 14 months
  src/Particular.LicensingComponent.Contracts/EndpointThroughputSummary.cs
  src/Particular.LicensingComponent.Contracts/ThroughputSettings.cs
  src/Particular.LicensingComponent.UnitTests/Infrastructure/DataStoreBuilder.cs
  src/Particular.LicensingComponent.UnitTests/ThroughputCollector/ThroughputCollector_ThroughputSummary_Tests.cs
  src/Particular.LicensingComponent/ThroughputCollector.cs
  src/Particular.LicensingComponent/ThroughputDataExtensions.cs
  src/ServiceControl.LicenseManagement/LicenseDetails.cs
  src/ServiceControl.Persistence.RavenDB/Throughput/LicensingDataStore.cs
  src/ServiceControl/Licensing/LicensingComponent.cs
Labels: Bug

#4858 Also support `ServiceControl.Audit/IngestAuditMessages`
  src/ServiceControl.Audit/Infrastructure/Settings/Settings.cs
Labels: Improvement

#4868 Add a RavenDB dirty memory custom check
  src/ServiceControl.Audit.Persistence.RavenDB/CustomChecks/CheckDirtyMemory.cs
  src/ServiceControl.Audit.Persistence.RavenDB/MemoryInformationRetriever.cs
  src/ServiceControl.Audit.Persistence.RavenDB/RavenPersistence.cs
  src/ServiceControl.Audit.Persistence.Tests.RavenDB/ApprovalFiles/CustomCheckTests.VerifyCustomChecks.approved.txt
  src/ServiceControl.Persistence.RavenDB/CustomChecks/CheckDirtyMemory.cs
  src/ServiceControl.Persistence.RavenDB/MemoryInformationRetriever.cs
  src/ServiceControl.Persistence.RavenDB/RavenPersistence.cs
  src/ServiceControl.Persistence.Tests.RavenDB/ApprovalFiles/APIApprovals.CustomCheckDetails.approved.txt
  src/ServiceControl.Persistence.Tests.RavenDB/ApprovalFiles/CustomCheckTests.VerifyCustomChecks.approved.txt
Labels: Improvement

#4824 Allow JIT killing of Raven.Embedded.EmbeddedServer by tearing it down as part of stop sequence
  src/ServiceControl.Audit.Persistence.RavenDB/IRavenPersistenceLifecycle.cs
  src/ServiceControl.Audit.Persistence.RavenDB/RavenEmbeddedPersistenceLifecycle.cs
  src/ServiceControl.Audit.Persistence.RavenDB/RavenExternalPersistenceLifecycle.cs
  src/ServiceControl.Audit.Persistence.RavenDB/RavenPersistenceLifecycleHostedService.cs
  src/ServiceControl.Persistence.RavenDB/IRavenPersistenceLifecycle.cs
  src/ServiceControl.Persistence.RavenDB/RavenEmbeddedPersistenceLifecycle.cs
  src/ServiceControl.Persistence.RavenDB/RavenExternalPersistenceLifecycle.cs
  src/ServiceControl.Persistence.RavenDB/RavenPersistenceLifecycleHostedService.cs
  src/ServiceControl.RavenDB/EmbeddedDatabase.cs
Labels: Improvement

#4755 Update to NServiceBus.RabbitMQ 10.0.0 and use management client
  .reposync.yml
  src/Directory.Packages.props
  src/NServiceBus.snk
  src/ServiceControl.Config/Commands/ScmuCommandChecks.cs
  src/ServiceControl.Management.PowerShell/Validation/AcknowledgementValues.cs
  src/ServiceControl.Management.PowerShell/Validation/PowerShellCommandChecks.cs
  src/ServiceControl.Transports.RabbitMQ/ConnectionConfiguration.cs
  src/ServiceControl.Transports.RabbitMQ/ConnectionFactory.cs
  src/ServiceControl.Transports.RabbitMQ/IManagementClientProvider.cs
  src/ServiceControl.Transports.RabbitMQ/QueueLengthProvider.cs
  src/ServiceControl.Transports.RabbitMQ/RabbitMQBrokerQueue.cs
  src/ServiceControl.Transports.RabbitMQ/RabbitMQConventionalRoutingTransportCustomization.cs
  src/ServiceControl.Transports.RabbitMQ/RabbitMQDirectRoutingTransportCustomization.cs
  src/ServiceControl.Transports.RabbitMQ/RabbitMQQuery.cs
  src/ServiceControl.Transports.RabbitMQ/RabbitMQTransportExtensions.cs
  src/ServiceControl.Transports.RabbitMQ/ServiceControl.Transports.RabbitMQ.csproj
  src/ServiceControl.Transports.RabbitMQ/TransportConfigurationExtensions.cs
  src/ServiceControl.Transports.RabbitMQ/transport.manifest
  src/ServiceControl.Transports.RabbitMQClassicConventionalRouting.Tests/RabbitMQQueryTests.cs
  src/ServiceControl.Transports.RabbitMQQuorumDirectRouting.Tests/ApprovalFiles/RabbitMQQueryTests.TestConnectionWithInvalidSettings.approved.txt
  src/ServiceControl.Transports.RabbitMQQuorumDirectRouting.Tests/ApprovalFiles/RabbitMQQueryTests.TestConnectionWithValidSettings.approved.txt
  src/ServiceControl.Transports.RabbitMQQuorumDirectRouting.Tests/ApprovalFiles/RabbitMQQuery_ResponseParsing_Tests.Should_fetch_queue_details_in_old_format.approved.txt
  src/ServiceControl.Transports.RabbitMQQuorumDirectRouting.Tests/ApprovalFiles/RabbitMQQuery_ResponseParsing_Tests.Should_handle_duplicated_json_data.approved.txt
  src/ServiceControl.Transports.RabbitMQQuorumDirectRouting.Tests/RabbitMQQueryTests.cs
  src/ServiceControl.Transports.RabbitMQQuorumDirectRouting.Tests/RabbitMQQuery_ResponseParsing_Tests.cs
  src/ServiceControl.Transports.RabbitMQQuorumDirectRouting.Tests/ServiceControl.Transports.RabbitMQQuorumDirectRouting.Tests.csproj
  src/ServiceControl.Transports.Tests/QueueLengthMonitoringTests.cs
  src/ServiceControl.Transports.Tests/TransportTestFixture.cs
  src/ServiceControl.Transports/BrokerThroughput/IBrokerQueue.cs
  src/ServiceControl.Transports/ServiceControl.Transports.csproj
  src/ServiceControlInstaller.Engine/Configuration/ServiceControl/ServiceControlAppConfig.cs
  src/ServiceControlInstaller.Engine/Configuration/ServiceControl/SettingsList.cs
  src/ServiceControlInstaller.Engine/Interfaces.cs
  src/ServiceControlInstaller.Engine/Validation/AbstractCommandChecks.cs
  src/TestHelper/TestHelper.csproj
Labels: Feature

#4907 ManagementApiUrl Does Not Actually Support HTTPS
  src/Directory.Packages.props
Labels: Bug

#4905 ServiceControl Audit Ingestion throwing NREs with audit forwarding enabled
  src/ServiceControl.Audit/Auditing/AuditIngestor.cs
Labels: Bug
